apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  name: {{ include "proxyme.fullname" . }}
  labels:
    {{- include "proxyme.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "proxyme.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "proxyme.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Chart.Name }}
        env:
          - name: PROXY_NOAUTH
            valueFrom:
              configMapKeyRef:
                key: PROXY_NOAUTH
                name: {{.Chart.Name}}-{{.Release.Name}}-config
          - name: PROXY_USERS
            valueFrom:
              configMapKeyRef:
                key: PROXY_USERS
                name: {{.Chart.Name}}-{{.Release.Name}}-config
        ports:
          - name: socks5
            containerPort: {{ .Values.socks5.port }}
            protocol: TCP
        startupProbe:
          tcpSocket:
            port: socks5
          periodSeconds: 1
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: socks5
          periodSeconds: 10
          successThreshold: 1
        livenessProbe:
          tcpSocket:
            port: socks5
          periodSeconds: 5
          failureThreshold: 1
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
            add: [ "NET_BIND_SERVICE" ]
        resources:
          {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
status: {}
