# app specific options
socks5:
  noauth: "true"
#  users: "user:pass"

service:
  type: LoadBalancer
  port: 1080
#  nodePort: 0

# kubernetes options
replicaCount: 1

imagePullSecrets: []

podAnnotations: {}
podLabels: {}

resources:
  limits:
    cpu: 5m
    memory: 50Mi
  requests:
    cpu: 5m
    memory: 20Mi

nodeSelector: {}
tolerations: []
affinity: {}
